### PR TITLE
Update for shasht fixes

### PR DESCRIPTION
**Pull request by yitzchak**
Obviously these fixes are not in quicklisp yet so I understand if you want to wait until they are. Also completely understand if you want to rephrase in your own style.

I added methods for characters and multidimensional arrays to shasht. Also, I fixed the `NIL` hang issue.

There are other things that I would like to tweak (like number formatting, key interning, and pretty printing), but that may take time.

Thanks again!

### CODE REVIEW

**Comment by sabracrolleton** [comment]
Great. I am combining your patches with a bunch of typo corrections and a lot of custom_id orgmode stuff into a push from my side. 

Updating today and including a note in the changelog that if people rely on quicklisp, today's improvements will be in the next quicklisp version but are in the github version now.

**Comment by yitzchak** [comment]
Awesome. I think the `:NULL` <- `null` in the shasht default mapping should be a two way mapping: `:NULL` <-> `null`. That is provided I understand the table correctly. 

Looks like you got everything else!

**Comment by sabracrolleton** [comment]
Thanks. Will fix that right now.

**Comment by sabracrolleton** [comment]
Will close pull request since we got everything in a different PR.

**Pull request closed without merging**
